/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiCheckRouteImport } from './routes/api/check'
import { Route as ApiCheckIdRouteImport } from './routes/api/check.$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckRoute = ApiCheckRouteImport.update({
  id: '/api/check',
  path: '/api/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckIdRoute = ApiCheckIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCheckRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/check': typeof ApiCheckRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/report/$id': typeof ReportIdRoute
  '/api/check/$id': typeof ApiCheckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/check': typeof ApiCheckRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/report/$id': typeof ReportIdRoute
  '/api/check/$id': typeof ApiCheckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/check': typeof ApiCheckRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/report/$id': typeof ReportIdRoute
  '/api/check/$id': typeof ApiCheckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/check'
    | '/api/config'
    | '/report/$id'
    | '/api/check/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/check'
    | '/api/config'
    | '/report/$id'
    | '/api/check/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/check'
    | '/api/config'
    | '/report/$id'
    | '/api/check/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiCheckRoute: typeof ApiCheckRouteWithChildren
  ApiConfigRoute: typeof ApiConfigRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check': {
      id: '/api/check'
      path: '/api/check'
      fullPath: '/api/check'
      preLoaderRoute: typeof ApiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check/$id': {
      id: '/api/check/$id'
      path: '/$id'
      fullPath: '/api/check/$id'
      preLoaderRoute: typeof ApiCheckIdRouteImport
      parentRoute: typeof ApiCheckRoute
    }
  }
}

interface ApiCheckRouteChildren {
  ApiCheckIdRoute: typeof ApiCheckIdRoute
}

const ApiCheckRouteChildren: ApiCheckRouteChildren = {
  ApiCheckIdRoute: ApiCheckIdRoute,
}

const ApiCheckRouteWithChildren = ApiCheckRoute._addFileChildren(
  ApiCheckRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiCheckRoute: ApiCheckRouteWithChildren,
  ApiConfigRoute: ApiConfigRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
